fix: add unit test

diff --git a/.github/workflows/pr-checks.yaml b/.github/workflows/pr-checks.yaml
--- a/.github/workflows/pr-checks.yaml
+++ b/.github/workflows/pr-checks.yaml
@@ -1,37 +1,23 @@
-name: Test
-
 on:
-  workflow_dispatch:
   pull_request:
-
+  push:
+permissions:
+  contents: read
+  actions: read
+  checks: write
 jobs:
-  test:
-    permissions:
-      contents: write
-      issues: write
-      pull-requests: write
+  build-test:
+    name: Build & Test
     runs-on: ubuntu-latest
-
-    env:
-      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+      - uses: actions/checkout@v3     # checkout the repo
+      - run: npm install                   # install packages
+      - run: npm run test                 # run tests (configured to use jest-junit reporter)
 
-      - name: Setup Node.js
-        uses: actions/setup-node@v3
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          node-version: 18.18.2
-
-      - name: Install dependencies
-        run: npm install
-
-      - name: Build package
-        run: npm run test
-
-      - name: check new
-        uses: patriknyblad/add-pr-checks@v1.0.0
-        with:
-          token: ${{ secrets.GH_TOKEN }}
-          checks-path: 'sample-checks/*'
+          name: JEST Tests            # Name of the check run which will be created
+          path: reports/jest-*.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
